name: bettsix
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"


dependencies:
  flame:
  flame_forge2d: ^0.13.0+1
  another_flushbar: ^1.12.30
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  shared_preferences:
  provider: ^6.1.2
  fluttertoast: ^8.2.4
  dio: ^5.4.0
  flutter_widget_from_html:
  flutter_share:
  url_launcher:
  webview_flutter:
  image_picker:
  just_audio:
  audioplayers:
  animated_text_kit:
  dotted_border:
  connectivity_plus:
  url_strategy:
  share_plus:
  http:
  socket_io_client:
  draggable_fab:
  add_to_cart_animation:
  fwfh_text_style:
  page_transition:
  flutter_flip_card:
  wakelock_plus:
  install_plugin:
  file_picker:
  #new setup
  shimmer:
  flutter_styled_toast:
  country_code_picker:
  curved_navigation_bar:
  flutter_bloc:
  iconly:
  marquee:
  lottie:
  get:
  flutter_svg:


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true
  assets:
    - assetss/images/
    - assetss/images/coin/
    - assetss/images/robot/
    - assetss/images/explosion/
    - assetss/
    - assets/
    - assets/lottie/
#    - assets/vip/
    - assets/chips/
    - assets/icons/
#    - assets/mines/
    - assets/music/
    - assets/images/
    - assets/person/
    - assets/svg/
    - assets/win_go/
    - assets/aviator/
    - assets/category/
    - assets/andarbahar/
    - assets/dragontiger/
    - assets/cards/


